@startuml
actor User
boundary Index.jsp
participant login.class
participant FrontController
participant UserMapper
database CupcakeDatabase


User -> Index.jsp : username & password
Index.jsp -> FrontController: http POST login
FrontController -> UserMapper: validate()
UserMapper ->  CupcakeDatabase: executeQuery()
CupcakeDatabase -> UserMapper: resultset
UserMapper -> UserMapper: validate resultset
UserMapper -> FrontController: OK
FrontController -> Index.jsp: forward
Index.jsp -> User: Welcome
@enduml