@startuml
actor Buyer
boundary Checkout.jsp
participant FrontController
participant Command
participant Payment
participant LogicFacade
participant ProductMapper
database CupcakeDatabase


Buyer -> Checkout.jsp : Betal
Checkout.jsp -> FrontController: Request
FrontController -> Command: getCommand
Command -> FrontController: returnCommand
FrontController -> Payment: executeCommand
Payment ->  ProductMapper: execute()
LogicFacade -> ProductMapper: updateCredit()
ProductMapper -> CupcakeDatabase: updateCreditQuery()
CupcakeDatabase -> FrontController: OK
FrontController -> Checkout.jsp: forward
Checkout.jsp -> Buyer: Køb Godkendt
@enduml